### ISSUE TITLE
vqgan

### ISSUE THREAD

**Issue by 1090h2400** [Qiyuan-Ge/PaintMind#1]
Wow, that's great！ Is this project the code for Vector-quantized Image Modeling with Improved VQGAN？

**Comment by Qiyuan-Ge** [comment]
Hi, I referred to that paper, but there are still some differences, for example, I am still using PatchGAN instead of StyleGAN(may try it in the future). Except that, I try to improve the vit architecture, like adding memory efficient attention from xformers and replacing GeLU to SwishGLU(from palm and llama)

**Comment by 1090h2400** [comment]
> Hi, I referred to that paper, but there are still some differences, for example, I am still using PatchGAN instead of StyleGAN(may try it in the future). Except that, I try to improve the vit architecture, like adding memory efficient attention from xformers and replacing GeLU to SwishGLU(from palm and llama)

Anyway, thanks for your work. and an error occurred in the loading of the weight. The key of the weight and the key of the model do not match. The model or weights have been modified?

**Comment by Qiyuan-Ge** [comment]
Sorry, I explained that in README:
- 2023/4/19  
Note: Hi, I am preparing for a new release with better vitvqgan and generate model, pretrained weights 
from old version will not be available.
Recently, I will release a stable version trained on a much bigger dataset.

**Comment by 1090h2400** [comment]
> Sorry, I explained that in README:
> 
> * 2023/4/19
>   Note: Hi, I am preparing for a new release with better vitvqgan and generate model, pretrained weights
>   from old version will not be available.
>   Recently, I will release a stable version trained on a much bigger dataset.

Oh, I ignored this important information
