### ISSUE TITLE
high resolution model

### ISSUE THREAD

**Issue by pranoyr** [Qiyuan-Ge/PaintMind#3]
Are you working on the high resolution Image Generation?

**Comment by Qiyuan-Ge** [comment]
Hi, I am current  focus on the other projects.

**Comment by pranoyr** [comment]
Can I work on the high res model.

**Comment by Qiyuan-Ge** [comment]
> Can I work on the high res model.

Certainly! Greatly welcome your continued efforts in improving this work.
